name: my_blogapp_frontend
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  #State Managament
  get: ^4.6.5
  #Local Storage
  get_storage:
  #GraphQL
  graphql_flutter: ^5.1.2
  #Provides functional programming tools for Dart.
  dartz:
  #	Loads environment variables from a .env file into Dart's environment variables.
  flutter_dotenv: ^5.1.0
  # A library for loading and caching network images in Flutter.
  cached_network_image: ^3.4.1
  #Simplifies value equality in Dart objects.
  equatable:
  #A plugin for launching URLs in the browser or other applications.
  url_launcher:
  #Converts URLs in text to clickable links in Flutter.
  flutter_linkify:
  #A package providing staggered grid views for Flutter.
  flutter_staggered_grid_view: ^0.4.0
  #Allows easy use of Google Fonts in Flutter applications.
  google_fonts:
  #Provides internationalization and localization facilities, including date and number formatting.
  intl: ^0.19.0
  #A package providing Ionicons icon set for Flutter.
  ionicons: ^0.2.2
  #A collection of animated text widgets for Flutter.
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/